### ISSUE TITLE
Duplicating frames

### ISSUE THREAD

**Issue by vovazhuruk** [LonicaMewinsky/sd-webui-keyframer#1]
For some reason if I upload any count of frames (4, 8, 9), the on the grid I see duplications and don't see one of the frames. For example, I upload 4 frames: 1.png, 2.png, 3.png, 4.png. After generation grid of 2x2, the 2 first images on it are duplicates. Such as 2.png, 2.png, 3.png, 4.png. But I don't see the 1st image. I tested out with different image sizes, different images at all, different names, upload locations etc

Thanks!

**Comment by LonicaMewinsky** [comment]
Thanks a bunch. Just updated to correct this. Mind giving it another try?

**Comment by vovazhuruk** [comment]
Thanks! Gonna try

**Comment by vovazhuruk** [comment]
Now it works. Thanks!
